#!/usr/bin/env python3
"""Generate LAMMPS GCMC inputs for the cross-code check (10, 20, 30 bar, 304 K).

Protocol (decided 2026-09-21, see NOTES.md "Phase 4"):
  * MC only, NO time integration. `fix gcmc` then performs exchanges AND rigid-body
    translations/rotations of whole molecules, exactly as RASPA does, and the CO2
    geometry can never change. `fix rigid`/`fix shake` are deliberately NOT used:
    the LAMMPS docs restrict that combination to exchange moves only (M must be 0),
    which would force translations to come from MD instead.
  * Intramolecular interactions are excluded through the bond topology of the
    molecule template (`bond_style zero` + `special_bonds lj/coul 0 0 0`), which
    also corrects the Ewald reciprocal term. `neigh_modify exclude` would NOT
    correct kspace and is not used for that purpose.
  * The reservoir is matched to RASPA by passing the pressure together with
    RASPA's own Peng-Robinson fugacity coefficient for that point.
  * Framework-framework pair interactions are excluded from the neighbour list:
    the framework is rigid, so that term is a constant and cancels in every MC
    energy difference. It only makes the full-energy evaluations cheaper. (The
    reciprocal-space part still contains it, also as a constant.)
  * `full_energy` is applied automatically by LAMMPS with kspace and tail
    corrections, so every trial move costs a full energy evaluation.

Usage:
  python scripts/make_lammps_gcmc.py --data runs/crosscheck/lammps/B_framework.data \
      --mol runs/crosscheck/lammps/CO2.mol --out runs/crosscheck/gcmc [--steps 20000]
"""
import argparse
import shutil
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
ATM_PER_BAR = 1.0 / 1.01325
EPS_KCAL = {1: 0.5049973436, 2: 0.0599995234, 3: 0.1049890714, 4: 0.0440000000,
            5: 0.0536553299, 6: 0.1569837653}
SIGMA = {1: 4.008200, 2: 3.118100, 3: 3.430900, 4: 2.571100, 5: 2.800000, 6: 3.050000}

TEMPLATE = """# GCMC of CO2 in rigid MIL-53(Al) lp, {p_bar:g} bar, {T:g} K -- cross-code check against RASPA
# generated by scripts/make_lammps_gcmc.py
units real
atom_style full
boundary p p p
bond_style zero
special_bonds lj/coul 0.0 0.0 0.0        # intramolecular exclusions, kspace-corrected
pair_style lj/cut/coul/long 12.0 12.0    # same cut-off as RASPA
kspace_style ewald 1.0e-6                # RASPA: EwaldPrecision 1e-6 (different criterion)

read_data {data} extra/bond/per/atom 2 extra/special/per/atom 4
pair_modify mix arithmetic tail yes      # Lorentz-Berthelot + analytic tail correction
{pair_coeffs}
bond_coeff 1

group framework type 1 2 3 4
group co2 type 5 6                       # empty at start; fix gcmc adds inserted atoms
neigh_modify exclude group framework framework   # rigid host: constant term, cancels in dE
neigh_modify every 1 delay 0 check yes

molecule CO2 {mol}

# fix ID group gcmc N X M type seed T mu displace
# N=1: every step, X exchange attempts and M translation/rotation attempts on CO2
fix gcmc_co2 co2 gcmc 1 {nexch} {nmove} 0 {seed} {T:g} 0.0 {displace} mol CO2 &
    pressure {p_atm:.6f} fugacity_coeff {phi:.6f} maxangle 30.0 full_energy

variable nmol equal count(co2)/3
variable nuc  equal count(co2)/3/{ncells}
thermo_style custom step v_nmol v_nuc pe evdwl ecoul elong press
thermo {thermo_every}
thermo_modify format float %16.6f

timestep 1.0                              # no integrator: MC only
# (reset_timestep is not allowed while fix gcmc is defined, so the step counter runs
#  continuously: production is every step > {equil})
run {equil}                               # equilibration
run {prod}                                # production (loading averaged from the log)
write_data final_{p_bar:g}bar.data nocoeff
"""


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", required=True)
    ap.add_argument("--mol", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--pressures-bar", nargs="+", type=float, default=[10.0, 20.0, 30.0])
    ap.add_argument("--temperature", type=float, default=304.0)
    ap.add_argument("--ncells", type=int, default=16)
    ap.add_argument("--nexch", type=int, default=20, help="exchange attempts per step")
    ap.add_argument("--nmove", type=int, default=20, help="translation/rotation attempts per step")
    ap.add_argument("--displace", type=float, default=0.35)
    ap.add_argument("--equil", type=int, default=2000)
    ap.add_argument("--prod", type=int, default=20000)
    ap.add_argument("--thermo-every", type=int, default=100)
    ap.add_argument("--seed", type=int, default=49281)
    a = ap.parse_args(argv)

    # RASPA's Peng-Robinson fugacity coefficients for these points
    iso = pd.read_csv(ROOT / "results" / "isotherm_MIL53_lp_CO2_304K.csv", comment="#")
    phi = dict(zip(iso.p_bar.round(6), iso.fugacity_coeff))
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    pair_coeffs = "\n".join(f"pair_coeff {t} {t} {EPS_KCAL[t]:.10f} {SIGMA[t]:.6f}" for t in sorted(EPS_KCAL))
    for p_bar in a.pressures_bar:
        if round(p_bar, 6) not in phi:
            sys.exit(f"no RASPA fugacity coefficient for {p_bar} bar; run scripts/isotherm.py first")
        d = out / f"p_{p_bar:g}bar"
        d.mkdir(exist_ok=True)
        shutil.copy(a.data, d / Path(a.data).name)
        shutil.copy(a.mol, d / Path(a.mol).name)
        (d / "in.gcmc").write_text(TEMPLATE.format(
            p_bar=p_bar, T=a.temperature, data=Path(a.data).name, mol=Path(a.mol).name,
            pair_coeffs=pair_coeffs, ncells=a.ncells, nexch=a.nexch, nmove=a.nmove,
            displace=a.displace, seed=a.seed + int(p_bar), p_atm=p_bar * ATM_PER_BAR,
            phi=phi[round(p_bar, 6)], equil=a.equil, prod=a.prod, thermo_every=a.thermo_every))
        print(f"wrote {d}  (p = {p_bar:g} bar = {p_bar * ATM_PER_BAR:.4f} atm, "
              f"phi = {phi[round(p_bar, 6)]:.6f})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
